FROM maven:3.9.9-eclipse-temurin-24
WORKDIR /app
COPY . .
RUN mvn dependency:go-offline
CMD ["mvn", "spring-boot:run", "-Dspring-boot.run.jvmArguments=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005"]